InClass09/Controllers/TvcLoaiSanPhamsController.cs
using InClass08.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InClass08.Controllers
{
    public class TvcLoaiSanPhamsController : Controller
    {
        private readonly tvcInClass09LabCFContext _context;

        public TvcLoaiSanPhamsController(tvcInClass09LabCFContext context)
        {
            _context = context;
        }

        // GET: TvcLoaiSanPhams
        public async Task<IActionResult> Index()
        {
            return View(await _context.tvcLoaiSanPhams.ToListAsync());
        }

        // GET: TvcLoaiSanPhams/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tvcLoaiSanPham = await _context.tvcLoaiSanPhams
                .FirstOrDefaultAsync(m => m.tvcId == id);
            if (tvcLoaiSanPham == null)
            {
                return NotFound();
            }

            return View(tvcLoaiSanPham);
        }

        // GET: TvcLoaiSanPhams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TvcLoaiSanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("tvcId,tvcMaLoai,tvcTenLoai,tvcTrangThai")] TvcLoaiSanPham tvcLoaiSanPham)
        {
            ModelState.Remove(nameof(TvcLoaiSanPham.TvcSanPham));
            if (ModelState.IsValid)
            {
                _context.Add(tvcLoaiSanPham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tvcLoaiSanPham);
        }

        // GET: TvcLoaiSanPhams/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tvcLoaiSanPham = await _context.tvcLoaiSanPhams.FindAsync(id);
            if (tvcLoaiSanPham == null)
            {
                return NotFound();
            }
            return View(tvcLoaiSanPham);
        }

        // POST: TvcLoaiSanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("tvcId,tvcMaLoai,tvcTenLoai,tvcTrangThai")] TvcLoaiSanPham tvcLoaiSanPham)
        {
            ModelState.Remove(nameof(TvcLoaiSanPham.TvcSanPham));

            if (id != tvcLoaiSanPham.tvcId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tvcLoaiSanPham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TvcLoaiSanPhamExists(tvcLoaiSanPham.tvcId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tvcLoaiSanPham);
        }

        // GET: TvcLoaiSanPhams/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tvcLoaiSanPham = await _context.tvcLoaiSanPhams
                .FirstOrDefaultAsync(m => m.tvcId == id);
            if (tvcLoaiSanPham == null)
            {
                return NotFound();
            }

            return View(tvcLoaiSanPham);
        }

        // POST: TvcLoaiSanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var tvcLoaiSanPham = await _context.tvcLoaiSanPhams.FindAsync(id);
            if (tvcLoaiSanPham != null)
            {
                _context.tvcLoaiSanPhams.Remove(tvcLoaiSanPham);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TvcLoaiSanPhamExists(long id)
        {
            return _context.tvcLoaiSanPhams.Any(e => e.tvcId == id);
        }
    }
}

InClass09/Controllers/TvcSanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InClass08.Models;

namespace InClass08.Controllers
{
    public class TvcSanPhamsController : Controller
    {
        private readonly tvcInClass09LabCFContext _context;

        public TvcSanPhamsController(tvcInClass09LabCFContext context)
        {
            _context = context;
        }

        // GET: TvcSanPhams
        public async Task<IActionResult> Index()
        {
            var tvcInClass09LabCFContext = _context.tvcSanPhams.Include(t => t.TvcLoaiSanPham);
            return View(await tvcInClass09LabCFContext.ToListAsync());
        }

        // GET: TvcSanPhams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tvcSanPham = await _context.tvcSanPhams
                .Include(t => t.TvcLoaiSanPham)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tvcSanPham == null)
            {
                return NotFound();
            }

            return View(tvcSanPham);
        }

        // GET: TvcSanPhams/Create
        public IActionResult Create()
        {
            ViewData["tvcLoaiSanPhamId"] = new SelectList(_context.tvcLoaiSanPhams, "tvcId", "tvcId");
            return View();
        }

        // POST: TvcSanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("tvcMaSanPham,tvcTenSanPham,tvcHinhAnh,tvcSoLuong,tvcDonGia,tvcLoaiSanPhamId")] TvcSanPham tvcSanPham)
        {
            ModelState.Remove(nameof(TvcSanPham.TvcLoaiSanPham));
            
            if (ModelState.IsValid)
            {
                _context.Add(tvcSanPham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["tvcLoaiSanPhamId"] = new SelectList(_context.tvcLoaiSanPhams, "tvcId", "tvcTenLoai", tvcSanPham.tvcLoaiSanPhamId);
            return View(tvcSanPham);
        }

        // GET: TvcSanPhams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tvcSanPham = await _context.tvcSanPhams.FindAsync(id);
            if (tvcSanPham == null)
            {
                return NotFound();
            }
            ViewData["tvcLoaiSanPhamId"] = new SelectList(_context.tvcLoaiSanPhams, "tvcId", "tvcTenLoai", tvcSanPham.tvcLoaiSanPhamId);
            return View(tvcSanPham);
        }

        // POST: TvcSanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,tvcMaSanPham,tvcTenSanPham,tvcHinhAnh,tvcSoLuong,tvcDonGia,tvcLoaiSanPhamId")] TvcSanPham tvcSanPham)
        {
            ModelState.Remove(nameof(TvcSanPham.TvcLoaiSanPham));
            if (id != tvcSanPham.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tvcSanPham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TvcSanPhamExists(tvcSanPham.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["tvcLoaiSanPhamId"] = new SelectList(_context.tvcLoaiSanPhams, "tvcId", "tvcTenLoai", tvcSanPham.tvcLoaiSanPhamId);
            return View(tvcSanPham);
        }

        // GET: TvcSanPhams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tvcSanPham = await _context.tvcSanPhams
                .Include(t => t.TvcLoaiSanPham)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tvcSanPham == null)
            {
                return NotFound();
            }

            return View(tvcSanPham);
        }

        // POST: TvcSanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tvcSanPham = await _context.tvcSanPhams.FindAsync(id);
            if (tvcSanPham != null)
            {
                _context.tvcSanPhams.Remove(tvcSanPham);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TvcSanPhamExists(int id)
        {
            return _context.tvcSanPhams.Any(e => e.Id == id);
        }
    }
}

InClass09/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InClass08</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InClass08.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InClass08</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TvcSanPhams" asp-action="Index">TvcSanPhams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TvcLoaiSanPhams" asp-action="Index">TvcLoaiSanPhams</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
        
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InClass08 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>